### ISSUE TITLE
FAQ webview

### ISSUE THREAD

**Issue by ngrad** [sunlightlabs/design#65] opened 2015-04-29 15:08 UTC
As a user, I can reference an FAQ page to answer common questions or issues that come up with my process in emailing Congress.

**Comment by heyitsolivia** [comment] 2015-05-04 17:00
Duplicate of this issue in phantom mask: https://github.com/sunlightlabs/the-phantom-mask/issues/13

**Closed as completed by heyitsolivia** 2015-05-04 17:00 UTC
Labels: duplicate, design
